/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AiGuideRouteImport } from './routes/ai-guide'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ExploreNearMeRouteImport } from './routes/explore-near-me'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as TranslatorRouteImport } from './routes/translator'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedVerifierRouteRouteImport } from './routes/_authenticated/verifier/route'
import { Route as ApiBookingsRouteImport } from './routes/api.bookings'
import { Route as ApiReviewsRouteImport } from './routes/api.reviews'
import { Route as DestinationsIndexRouteImport } from './routes/destinations/index'
import { Route as DestinationsDestinationRouteImport } from './routes/destinations/$destination'
import { Route as GuidesGuideIdRouteImport } from './routes/guides/$guideId'
import { Route as ItineraryItineraryIdRouteImport } from './routes/itinerary/$itineraryId'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesServiceIdRouteImport } from './routes/services/$serviceId'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin/bookings'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin/providers'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin/services'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin/withdrawals'
import { Route as AuthenticatedGuideDashboardRouteImport } from './routes/_authenticated/guide/dashboard'
import { Route as AuthenticatedGuideMessagesRouteImport } from './routes/_authenticated/guide/messages'
import { Route as AuthenticatedProviderAnalyticsRouteImport } from './routes/_authenticated/provider/analytics'
import { Route as AuthenticatedProviderBookingsRouteImport } from './routes/_authenticated/provider/bookings'
import { Route as AuthenticatedProviderCalendarRouteImport } from './routes/_authenticated/provider/calendar'
import { Route as AuthenticatedProviderCustomersRouteImport } from './routes/_authenticated/provider/customers'
import { Route as AuthenticatedProviderDashboardRouteImport } from './routes/_authenticated/provider/dashboard'
import { Route as AuthenticatedProviderMessagesRouteImport } from './routes/_authenticated/provider/messages'
import { Route as AuthenticatedProviderNotificationsRouteImport } from './routes/_authenticated/provider/notifications'
import { Route as AuthenticatedProviderProfileRouteImport } from './routes/_authenticated/provider/profile'
import { Route as AuthenticatedProviderReviewsRouteImport } from './routes/_authenticated/provider/reviews'
import { Route as AuthenticatedProviderServicesRouteImport } from './routes/_authenticated/provider/services'
import { Route as AuthenticatedProviderWalletRouteImport } from './routes/_authenticated/provider/wallet'
import { Route as AuthenticatedTouristDashboardRouteImport } from './routes/_authenticated/tourist/dashboard'
import { Route as AuthenticatedTouristItinerariesRouteImport } from './routes/_authenticated/tourist/itineraries'
import { Route as AuthenticatedTouristMessagesRouteImport } from './routes/_authenticated/tourist/messages'
import { Route as AuthenticatedTouristReviewsRouteImport } from './routes/_authenticated/tourist/reviews'
import { Route as AuthenticatedTouristWishlistRouteImport } from './routes/_authenticated/tourist/wishlist'
import { Route as AuthenticatedVerifierAvailabilityRouteImport } from './routes/_authenticated/verifier/availability'
import { Route as AuthenticatedVerifierCheckinCheckoutRouteImport } from './routes/_authenticated/verifier/checkin-checkout'
import { Route as AuthenticatedVerifierDashboardRouteImport } from './routes/_authenticated/verifier/dashboard'
import { Route as AuthenticatedVerifierGuestsRouteImport } from './routes/_authenticated/verifier/guests'
import { Route as AuthenticatedVerifierHotelsRouteImport } from './routes/_authenticated/verifier/hotels'
import { Route as AuthenticatedVerifierMessagesRouteImport } from './routes/_authenticated/verifier/messages'
import { Route as AuthenticatedVerifierPaymentsRouteImport } from './routes/_authenticated/verifier/payments'
import { Route as AuthenticatedVerifierProfileRouteImport } from './routes/_authenticated/verifier/profile'
import { Route as AuthenticatedVerifierReservationsRouteImport } from './routes/_authenticated/verifier/reservations'
import { Route as AuthenticatedVerifierReviewsRouteImport } from './routes/_authenticated/verifier/reviews'
import { Route as AuthenticatedVerifierRoomsRouteImport } from './routes/_authenticated/verifier/rooms'
import { Route as ApiAiChatRouteImport } from './routes/api.ai.chat'
import { Route as ApiAiItineraryRouteImport } from './routes/api.ai.itinerary'
import { Route as ApiAiTranslateRouteImport } from './routes/api.ai.translate'
import { Route as ApiBookingsBookingIdRouteImport } from './routes/api.bookings.$bookingId'
import { Route as ApiBookingsMyBookingsRouteImport } from './routes/api.bookings.my-bookings'
import { Route as ApiEmergencyNearbyRouteImport } from './routes/api.emergency.nearby'
import { Route as ApiPaymentsIdRouteImport } from './routes/api.payments.$id'
import { Route as ApiPaymentsCreateOrderRouteImport } from './routes/api.payments.create-order'
import { Route as ApiPaymentsFailureRouteImport } from './routes/api.payments.failure'
import { Route as ApiPaymentsVerifyRouteImport } from './routes/api.payments.verify'
import { Route as ApiProviderBookingsRouteImport } from './routes/api.provider.bookings'
import { Route as ApiReviewsIdRouteImport } from './routes/api.reviews.$id'
import { Route as AuthenticatedServicesServiceIdBookRouteImport } from './routes/_authenticated/services/$serviceId/book'
import { Route as AuthenticatedTouristBookingsIndexRouteImport } from './routes/_authenticated/tourist/bookings/index'
import { Route as AuthenticatedTouristBookingsBookingIdRouteImport } from './routes/_authenticated/tourist/bookings/$bookingId'
import { Route as AuthenticatedTouristPaymentsIndexRouteImport } from './routes/_authenticated/tourist/payments/index'
import { Route as AuthenticatedTouristPaymentsPaymentIdRouteImport } from './routes/_authenticated/tourist/payments/$paymentId'
import { Route as ApiBookingsBookingIdPaymentRouteImport } from './routes/api.bookings.$bookingId.payment'
import { Route as ApiReviewsIdResponseRouteImport } from './routes/api.reviews.$id.response'
import { Route as ApiServicesServiceIdAvailabilityRouteImport } from './routes/api.services.$serviceId.availability'
import { Route as AuthenticatedTouristBookingsBookingIdConfirmationRouteImport } from './routes/_authenticated/tourist/bookings/$bookingId.confirmation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGuideRoute = AiGuideRouteImport.update({
  id: '/ai-guide',
  path: '/ai-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreNearMeRoute = ExploreNearMeRouteImport.update({
  id: '/explore-near-me',
  path: '/explore-near-me',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslatorRoute = TranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerifierRouteRoute =
  AuthenticatedVerifierRouteRouteImport.update({
    id: '/verifier',
    path: '/verifier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsRoute = ApiReviewsRouteImport.update({
  id: '/api/reviews',
  path: '/api/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsDestinationRoute = DestinationsDestinationRouteImport.update({
  id: '/destinations/$destination',
  path: '/destinations/$destination',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGuideIdRoute = GuidesGuideIdRouteImport.update({
  id: '/guides/$guideId',
  path: '/guides/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryItineraryIdRoute = ItineraryItineraryIdRouteImport.update({
  id: '/itinerary/$itineraryId',
  path: '/itinerary/$itineraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedGuideDashboardRoute =
  AuthenticatedGuideDashboardRouteImport.update({
    id: '/guide/dashboard',
    path: '/guide/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuideMessagesRoute =
  AuthenticatedGuideMessagesRouteImport.update({
    id: '/guide/messages',
    path: '/guide/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderAnalyticsRoute =
  AuthenticatedProviderAnalyticsRouteImport.update({
    id: '/provider/analytics',
    path: '/provider/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderBookingsRoute =
  AuthenticatedProviderBookingsRouteImport.update({
    id: '/provider/bookings',
    path: '/provider/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderCalendarRoute =
  AuthenticatedProviderCalendarRouteImport.update({
    id: '/provider/calendar',
    path: '/provider/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderCustomersRoute =
  AuthenticatedProviderCustomersRouteImport.update({
    id: '/provider/customers',
    path: '/provider/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderDashboardRoute =
  AuthenticatedProviderDashboardRouteImport.update({
    id: '/provider/dashboard',
    path: '/provider/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderMessagesRoute =
  AuthenticatedProviderMessagesRouteImport.update({
    id: '/provider/messages',
    path: '/provider/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderNotificationsRoute =
  AuthenticatedProviderNotificationsRouteImport.update({
    id: '/provider/notifications',
    path: '/provider/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderProfileRoute =
  AuthenticatedProviderProfileRouteImport.update({
    id: '/provider/profile',
    path: '/provider/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderReviewsRoute =
  AuthenticatedProviderReviewsRouteImport.update({
    id: '/provider/reviews',
    path: '/provider/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderServicesRoute =
  AuthenticatedProviderServicesRouteImport.update({
    id: '/provider/services',
    path: '/provider/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderWalletRoute =
  AuthenticatedProviderWalletRouteImport.update({
    id: '/provider/wallet',
    path: '/provider/wallet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTouristDashboardRoute =
  AuthenticatedTouristDashboardRouteImport.update({
    id: '/tourist/dashboard',
    path: '/tourist/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTouristItinerariesRoute =
  AuthenticatedTouristItinerariesRouteImport.update({
    id: '/tourist/itineraries',
    path: '/tourist/itineraries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTouristMessagesRoute =
  AuthenticatedTouristMessagesRouteImport.update({
    id: '/tourist/messages',
    path: '/tourist/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTouristReviewsRoute =
  AuthenticatedTouristReviewsRouteImport.update({
    id: '/tourist/reviews',
    path: '/tourist/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTouristWishlistRoute =
  AuthenticatedTouristWishlistRouteImport.update({
    id: '/tourist/wishlist',
    path: '/tourist/wishlist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerifierAvailabilityRoute =
  AuthenticatedVerifierAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedVerifierRouteRoute,
  } as any)
const AuthenticatedVerifierCheckinCheckoutRoute =
  AuthenticatedVerifierCheckinCheckoutRouteImport.update({
    id: '/checkin-checkout',
    path: '/checkin-checkout',
    getParentRoute: () => AuthenticatedVerifierRouteRoute,
  } as any)
const AuthenticatedVerifierDashboardRoute =
  AuthenticatedVerifierDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedVerifierRouteRoute,
  } as any)
const AuthenticatedVerifierGuestsRoute =
  AuthenticatedVerifierGuestsRouteImport.update({
    id: '/guests',
    path: '/guests',
    getParentRoute: () => AuthenticatedVerifierRouteRoute,
  } as any)
const AuthenticatedVerifierHotelsRoute =
  AuthenticatedVerifierHotelsRouteImport.update({
    id: '/hotels',
    path: '/hotels',
    getParentRoute: () => AuthenticatedVerifierRouteRoute,
  } as any)
const AuthenticatedVerifierMessagesRoute =
  AuthenticatedVerifierMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedVerifierRouteRoute,
  } as any)
const AuthenticatedVerifierPaymentsRoute =
  AuthenticatedVerifierPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedVerifierRouteRoute,
  } as any)
const AuthenticatedVerifierProfileRoute =
  AuthenticatedVerifierProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedVerifierRouteRoute,
  } as any)
const AuthenticatedVerifierReservationsRoute =
  AuthenticatedVerifierReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedVerifierRouteRoute,
  } as any)
const AuthenticatedVerifierReviewsRoute =
  AuthenticatedVerifierReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedVerifierRouteRoute,
  } as any)
const AuthenticatedVerifierRoomsRoute =
  AuthenticatedVerifierRoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => AuthenticatedVerifierRouteRoute,
  } as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiItineraryRoute = ApiAiItineraryRouteImport.update({
  id: '/api/ai/itinerary',
  path: '/api/ai/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTranslateRoute = ApiAiTranslateRouteImport.update({
  id: '/api/ai/translate',
  path: '/api/ai/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsBookingIdRoute = ApiBookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => ApiBookingsRoute,
} as any)
const ApiBookingsMyBookingsRoute = ApiBookingsMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => ApiBookingsRoute,
} as any)
const ApiEmergencyNearbyRoute = ApiEmergencyNearbyRouteImport.update({
  id: '/api/emergency/nearby',
  path: '/api/emergency/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsIdRoute = ApiPaymentsIdRouteImport.update({
  id: '/api/payments/$id',
  path: '/api/payments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCreateOrderRoute = ApiPaymentsCreateOrderRouteImport.update({
  id: '/api/payments/create-order',
  path: '/api/payments/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsFailureRoute = ApiPaymentsFailureRouteImport.update({
  id: '/api/payments/failure',
  path: '/api/payments/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsVerifyRoute = ApiPaymentsVerifyRouteImport.update({
  id: '/api/payments/verify',
  path: '/api/payments/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderBookingsRoute = ApiProviderBookingsRouteImport.update({
  id: '/api/provider/bookings',
  path: '/api/provider/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsIdRoute = ApiReviewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiReviewsRoute,
} as any)
const AuthenticatedServicesServiceIdBookRoute =
  AuthenticatedServicesServiceIdBookRouteImport.update({
    id: '/services/$serviceId/book',
    path: '/services/$serviceId/book',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTouristBookingsIndexRoute =
  AuthenticatedTouristBookingsIndexRouteImport.update({
    id: '/tourist/bookings/',
    path: '/tourist/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTouristBookingsBookingIdRoute =
  AuthenticatedTouristBookingsBookingIdRouteImport.update({
    id: '/tourist/bookings/$bookingId',
    path: '/tourist/bookings/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTouristPaymentsIndexRoute =
  AuthenticatedTouristPaymentsIndexRouteImport.update({
    id: '/tourist/payments/',
    path: '/tourist/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTouristPaymentsPaymentIdRoute =
  AuthenticatedTouristPaymentsPaymentIdRouteImport.update({
    id: '/tourist/payments/$paymentId',
    path: '/tourist/payments/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiBookingsBookingIdPaymentRoute =
  ApiBookingsBookingIdPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => ApiBookingsBookingIdRoute,
  } as any)
const ApiReviewsIdResponseRoute = ApiReviewsIdResponseRouteImport.update({
  id: '/response',
  path: '/response',
  getParentRoute: () => ApiReviewsIdRoute,
} as any)
const ApiServicesServiceIdAvailabilityRoute =
  ApiServicesServiceIdAvailabilityRouteImport.update({
    id: '/api/services/$serviceId/availability',
    path: '/api/services/$serviceId/availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTouristBookingsBookingIdConfirmationRoute =
  AuthenticatedTouristBookingsBookingIdConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => AuthenticatedTouristBookingsBookingIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-guide': typeof AiGuideRoute
  '/emergency': typeof EmergencyRoute
  '/explore-near-me': typeof ExploreNearMeRoute
  '/hotels': typeof HotelsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/planner': typeof PlannerRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRoute
  '/tours': typeof ToursRoute
  '/translator': typeof TranslatorRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/verifier': typeof AuthenticatedVerifierRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/bookings': typeof ApiBookingsRouteWithChildren
  '/api/reviews': typeof ApiReviewsRouteWithChildren
  '/destinations/$destination': typeof DestinationsDestinationRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/itinerary/$itineraryId': typeof ItineraryItineraryIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/guide/dashboard': typeof AuthenticatedGuideDashboardRoute
  '/guide/messages': typeof AuthenticatedGuideMessagesRoute
  '/provider/analytics': typeof AuthenticatedProviderAnalyticsRoute
  '/provider/bookings': typeof AuthenticatedProviderBookingsRoute
  '/provider/calendar': typeof AuthenticatedProviderCalendarRoute
  '/provider/customers': typeof AuthenticatedProviderCustomersRoute
  '/provider/dashboard': typeof AuthenticatedProviderDashboardRoute
  '/provider/messages': typeof AuthenticatedProviderMessagesRoute
  '/provider/notifications': typeof AuthenticatedProviderNotificationsRoute
  '/provider/profile': typeof AuthenticatedProviderProfileRoute
  '/provider/reviews': typeof AuthenticatedProviderReviewsRoute
  '/provider/services': typeof AuthenticatedProviderServicesRoute
  '/provider/wallet': typeof AuthenticatedProviderWalletRoute
  '/tourist/dashboard': typeof AuthenticatedTouristDashboardRoute
  '/tourist/itineraries': typeof AuthenticatedTouristItinerariesRoute
  '/tourist/messages': typeof AuthenticatedTouristMessagesRoute
  '/tourist/reviews': typeof AuthenticatedTouristReviewsRoute
  '/tourist/wishlist': typeof AuthenticatedTouristWishlistRoute
  '/verifier/availability': typeof AuthenticatedVerifierAvailabilityRoute
  '/verifier/checkin-checkout': typeof AuthenticatedVerifierCheckinCheckoutRoute
  '/verifier/dashboard': typeof AuthenticatedVerifierDashboardRoute
  '/verifier/guests': typeof AuthenticatedVerifierGuestsRoute
  '/verifier/hotels': typeof AuthenticatedVerifierHotelsRoute
  '/verifier/messages': typeof AuthenticatedVerifierMessagesRoute
  '/verifier/payments': typeof AuthenticatedVerifierPaymentsRoute
  '/verifier/profile': typeof AuthenticatedVerifierProfileRoute
  '/verifier/reservations': typeof AuthenticatedVerifierReservationsRoute
  '/verifier/reviews': typeof AuthenticatedVerifierReviewsRoute
  '/verifier/rooms': typeof AuthenticatedVerifierRoomsRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/itinerary': typeof ApiAiItineraryRoute
  '/api/ai/translate': typeof ApiAiTranslateRoute
  '/api/bookings/$bookingId': typeof ApiBookingsBookingIdRouteWithChildren
  '/api/bookings/my-bookings': typeof ApiBookingsMyBookingsRoute
  '/api/emergency/nearby': typeof ApiEmergencyNearbyRoute
  '/api/payments/$id': typeof ApiPaymentsIdRoute
  '/api/payments/create-order': typeof ApiPaymentsCreateOrderRoute
  '/api/payments/failure': typeof ApiPaymentsFailureRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/provider/bookings': typeof ApiProviderBookingsRoute
  '/api/reviews/$id': typeof ApiReviewsIdRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/services/$serviceId/book': typeof AuthenticatedServicesServiceIdBookRoute
  '/tourist/bookings/$bookingId': typeof AuthenticatedTouristBookingsBookingIdRouteWithChildren
  '/tourist/payments/$paymentId': typeof AuthenticatedTouristPaymentsPaymentIdRoute
  '/api/bookings/$bookingId/payment': typeof ApiBookingsBookingIdPaymentRoute
  '/api/reviews/$id/response': typeof ApiReviewsIdResponseRoute
  '/api/services/$serviceId/availability': typeof ApiServicesServiceIdAvailabilityRoute
  '/tourist/bookings/': typeof AuthenticatedTouristBookingsIndexRoute
  '/tourist/payments/': typeof AuthenticatedTouristPaymentsIndexRoute
  '/tourist/bookings/$bookingId/confirmation': typeof AuthenticatedTouristBookingsBookingIdConfirmationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-guide': typeof AiGuideRoute
  '/emergency': typeof EmergencyRoute
  '/explore-near-me': typeof ExploreNearMeRoute
  '/hotels': typeof HotelsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/planner': typeof PlannerRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRoute
  '/tours': typeof ToursRoute
  '/translator': typeof TranslatorRoute
  '/wishlist': typeof WishlistRoute
  '/verifier': typeof AuthenticatedVerifierRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/bookings': typeof ApiBookingsRouteWithChildren
  '/api/reviews': typeof ApiReviewsRouteWithChildren
  '/destinations/$destination': typeof DestinationsDestinationRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/itinerary/$itineraryId': typeof ItineraryItineraryIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/destinations': typeof DestinationsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/guide/dashboard': typeof AuthenticatedGuideDashboardRoute
  '/guide/messages': typeof AuthenticatedGuideMessagesRoute
  '/provider/analytics': typeof AuthenticatedProviderAnalyticsRoute
  '/provider/bookings': typeof AuthenticatedProviderBookingsRoute
  '/provider/calendar': typeof AuthenticatedProviderCalendarRoute
  '/provider/customers': typeof AuthenticatedProviderCustomersRoute
  '/provider/dashboard': typeof AuthenticatedProviderDashboardRoute
  '/provider/messages': typeof AuthenticatedProviderMessagesRoute
  '/provider/notifications': typeof AuthenticatedProviderNotificationsRoute
  '/provider/profile': typeof AuthenticatedProviderProfileRoute
  '/provider/reviews': typeof AuthenticatedProviderReviewsRoute
  '/provider/services': typeof AuthenticatedProviderServicesRoute
  '/provider/wallet': typeof AuthenticatedProviderWalletRoute
  '/tourist/dashboard': typeof AuthenticatedTouristDashboardRoute
  '/tourist/itineraries': typeof AuthenticatedTouristItinerariesRoute
  '/tourist/messages': typeof AuthenticatedTouristMessagesRoute
  '/tourist/reviews': typeof AuthenticatedTouristReviewsRoute
  '/tourist/wishlist': typeof AuthenticatedTouristWishlistRoute
  '/verifier/availability': typeof AuthenticatedVerifierAvailabilityRoute
  '/verifier/checkin-checkout': typeof AuthenticatedVerifierCheckinCheckoutRoute
  '/verifier/dashboard': typeof AuthenticatedVerifierDashboardRoute
  '/verifier/guests': typeof AuthenticatedVerifierGuestsRoute
  '/verifier/hotels': typeof AuthenticatedVerifierHotelsRoute
  '/verifier/messages': typeof AuthenticatedVerifierMessagesRoute
  '/verifier/payments': typeof AuthenticatedVerifierPaymentsRoute
  '/verifier/profile': typeof AuthenticatedVerifierProfileRoute
  '/verifier/reservations': typeof AuthenticatedVerifierReservationsRoute
  '/verifier/reviews': typeof AuthenticatedVerifierReviewsRoute
  '/verifier/rooms': typeof AuthenticatedVerifierRoomsRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/itinerary': typeof ApiAiItineraryRoute
  '/api/ai/translate': typeof ApiAiTranslateRoute
  '/api/bookings/$bookingId': typeof ApiBookingsBookingIdRouteWithChildren
  '/api/bookings/my-bookings': typeof ApiBookingsMyBookingsRoute
  '/api/emergency/nearby': typeof ApiEmergencyNearbyRoute
  '/api/payments/$id': typeof ApiPaymentsIdRoute
  '/api/payments/create-order': typeof ApiPaymentsCreateOrderRoute
  '/api/payments/failure': typeof ApiPaymentsFailureRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/provider/bookings': typeof ApiProviderBookingsRoute
  '/api/reviews/$id': typeof ApiReviewsIdRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/services/$serviceId/book': typeof AuthenticatedServicesServiceIdBookRoute
  '/tourist/bookings/$bookingId': typeof AuthenticatedTouristBookingsBookingIdRouteWithChildren
  '/tourist/payments/$paymentId': typeof AuthenticatedTouristPaymentsPaymentIdRoute
  '/api/bookings/$bookingId/payment': typeof ApiBookingsBookingIdPaymentRoute
  '/api/reviews/$id/response': typeof ApiReviewsIdResponseRoute
  '/api/services/$serviceId/availability': typeof ApiServicesServiceIdAvailabilityRoute
  '/tourist/bookings': typeof AuthenticatedTouristBookingsIndexRoute
  '/tourist/payments': typeof AuthenticatedTouristPaymentsIndexRoute
  '/tourist/bookings/$bookingId/confirmation': typeof AuthenticatedTouristBookingsBookingIdConfirmationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-guide': typeof AiGuideRoute
  '/emergency': typeof EmergencyRoute
  '/explore-near-me': typeof ExploreNearMeRoute
  '/hotels': typeof HotelsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/planner': typeof PlannerRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRoute
  '/tours': typeof ToursRoute
  '/translator': typeof TranslatorRoute
  '/wishlist': typeof WishlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/verifier': typeof AuthenticatedVerifierRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/bookings': typeof ApiBookingsRouteWithChildren
  '/api/reviews': typeof ApiReviewsRouteWithChildren
  '/destinations/$destination': typeof DestinationsDestinationRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/itinerary/$itineraryId': typeof ItineraryItineraryIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/guide/dashboard': typeof AuthenticatedGuideDashboardRoute
  '/_authenticated/guide/messages': typeof AuthenticatedGuideMessagesRoute
  '/_authenticated/provider/analytics': typeof AuthenticatedProviderAnalyticsRoute
  '/_authenticated/provider/bookings': typeof AuthenticatedProviderBookingsRoute
  '/_authenticated/provider/calendar': typeof AuthenticatedProviderCalendarRoute
  '/_authenticated/provider/customers': typeof AuthenticatedProviderCustomersRoute
  '/_authenticated/provider/dashboard': typeof AuthenticatedProviderDashboardRoute
  '/_authenticated/provider/messages': typeof AuthenticatedProviderMessagesRoute
  '/_authenticated/provider/notifications': typeof AuthenticatedProviderNotificationsRoute
  '/_authenticated/provider/profile': typeof AuthenticatedProviderProfileRoute
  '/_authenticated/provider/reviews': typeof AuthenticatedProviderReviewsRoute
  '/_authenticated/provider/services': typeof AuthenticatedProviderServicesRoute
  '/_authenticated/provider/wallet': typeof AuthenticatedProviderWalletRoute
  '/_authenticated/tourist/dashboard': typeof AuthenticatedTouristDashboardRoute
  '/_authenticated/tourist/itineraries': typeof AuthenticatedTouristItinerariesRoute
  '/_authenticated/tourist/messages': typeof AuthenticatedTouristMessagesRoute
  '/_authenticated/tourist/reviews': typeof AuthenticatedTouristReviewsRoute
  '/_authenticated/tourist/wishlist': typeof AuthenticatedTouristWishlistRoute
  '/_authenticated/verifier/availability': typeof AuthenticatedVerifierAvailabilityRoute
  '/_authenticated/verifier/checkin-checkout': typeof AuthenticatedVerifierCheckinCheckoutRoute
  '/_authenticated/verifier/dashboard': typeof AuthenticatedVerifierDashboardRoute
  '/_authenticated/verifier/guests': typeof AuthenticatedVerifierGuestsRoute
  '/_authenticated/verifier/hotels': typeof AuthenticatedVerifierHotelsRoute
  '/_authenticated/verifier/messages': typeof AuthenticatedVerifierMessagesRoute
  '/_authenticated/verifier/payments': typeof AuthenticatedVerifierPaymentsRoute
  '/_authenticated/verifier/profile': typeof AuthenticatedVerifierProfileRoute
  '/_authenticated/verifier/reservations': typeof AuthenticatedVerifierReservationsRoute
  '/_authenticated/verifier/reviews': typeof AuthenticatedVerifierReviewsRoute
  '/_authenticated/verifier/rooms': typeof AuthenticatedVerifierRoomsRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/itinerary': typeof ApiAiItineraryRoute
  '/api/ai/translate': typeof ApiAiTranslateRoute
  '/api/bookings/$bookingId': typeof ApiBookingsBookingIdRouteWithChildren
  '/api/bookings/my-bookings': typeof ApiBookingsMyBookingsRoute
  '/api/emergency/nearby': typeof ApiEmergencyNearbyRoute
  '/api/payments/$id': typeof ApiPaymentsIdRoute
  '/api/payments/create-order': typeof ApiPaymentsCreateOrderRoute
  '/api/payments/failure': typeof ApiPaymentsFailureRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/provider/bookings': typeof ApiProviderBookingsRoute
  '/api/reviews/$id': typeof ApiReviewsIdRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/services/$serviceId/book': typeof AuthenticatedServicesServiceIdBookRoute
  '/_authenticated/tourist/bookings/$bookingId': typeof AuthenticatedTouristBookingsBookingIdRouteWithChildren
  '/_authenticated/tourist/payments/$paymentId': typeof AuthenticatedTouristPaymentsPaymentIdRoute
  '/api/bookings/$bookingId/payment': typeof ApiBookingsBookingIdPaymentRoute
  '/api/reviews/$id/response': typeof ApiReviewsIdResponseRoute
  '/api/services/$serviceId/availability': typeof ApiServicesServiceIdAvailabilityRoute
  '/_authenticated/tourist/bookings/': typeof AuthenticatedTouristBookingsIndexRoute
  '/_authenticated/tourist/payments/': typeof AuthenticatedTouristPaymentsIndexRoute
  '/_authenticated/tourist/bookings/$bookingId/confirmation': typeof AuthenticatedTouristBookingsBookingIdConfirmationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-guide'
    | '/emergency'
    | '/explore-near-me'
    | '/hotels'
    | '/login'
    | '/mcp'
    | '/planner'
    | '/register'
    | '/restaurants'
    | '/tours'
    | '/translator'
    | '/wishlist'
    | '/admin'
    | '/verifier'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/profile'
    | '/api/bookings'
    | '/api/reviews'
    | '/destinations/$destination'
    | '/guides/$guideId'
    | '/itinerary/$itineraryId'
    | '/services/$serviceId'
    | '/destinations/'
    | '/services/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/guide/dashboard'
    | '/guide/messages'
    | '/provider/analytics'
    | '/provider/bookings'
    | '/provider/calendar'
    | '/provider/customers'
    | '/provider/dashboard'
    | '/provider/messages'
    | '/provider/notifications'
    | '/provider/profile'
    | '/provider/reviews'
    | '/provider/services'
    | '/provider/wallet'
    | '/tourist/dashboard'
    | '/tourist/itineraries'
    | '/tourist/messages'
    | '/tourist/reviews'
    | '/tourist/wishlist'
    | '/verifier/availability'
    | '/verifier/checkin-checkout'
    | '/verifier/dashboard'
    | '/verifier/guests'
    | '/verifier/hotels'
    | '/verifier/messages'
    | '/verifier/payments'
    | '/verifier/profile'
    | '/verifier/reservations'
    | '/verifier/reviews'
    | '/verifier/rooms'
    | '/api/ai/chat'
    | '/api/ai/itinerary'
    | '/api/ai/translate'
    | '/api/bookings/$bookingId'
    | '/api/bookings/my-bookings'
    | '/api/emergency/nearby'
    | '/api/payments/$id'
    | '/api/payments/create-order'
    | '/api/payments/failure'
    | '/api/payments/verify'
    | '/api/provider/bookings'
    | '/api/reviews/$id'
    | '/admin/'
    | '/services/$serviceId/book'
    | '/tourist/bookings/$bookingId'
    | '/tourist/payments/$paymentId'
    | '/api/bookings/$bookingId/payment'
    | '/api/reviews/$id/response'
    | '/api/services/$serviceId/availability'
    | '/tourist/bookings/'
    | '/tourist/payments/'
    | '/tourist/bookings/$bookingId/confirmation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-guide'
    | '/emergency'
    | '/explore-near-me'
    | '/hotels'
    | '/login'
    | '/mcp'
    | '/planner'
    | '/register'
    | '/restaurants'
    | '/tours'
    | '/translator'
    | '/wishlist'
    | '/verifier'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/profile'
    | '/api/bookings'
    | '/api/reviews'
    | '/destinations/$destination'
    | '/guides/$guideId'
    | '/itinerary/$itineraryId'
    | '/services/$serviceId'
    | '/destinations'
    | '/services'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/guide/dashboard'
    | '/guide/messages'
    | '/provider/analytics'
    | '/provider/bookings'
    | '/provider/calendar'
    | '/provider/customers'
    | '/provider/dashboard'
    | '/provider/messages'
    | '/provider/notifications'
    | '/provider/profile'
    | '/provider/reviews'
    | '/provider/services'
    | '/provider/wallet'
    | '/tourist/dashboard'
    | '/tourist/itineraries'
    | '/tourist/messages'
    | '/tourist/reviews'
    | '/tourist/wishlist'
    | '/verifier/availability'
    | '/verifier/checkin-checkout'
    | '/verifier/dashboard'
    | '/verifier/guests'
    | '/verifier/hotels'
    | '/verifier/messages'
    | '/verifier/payments'
    | '/verifier/profile'
    | '/verifier/reservations'
    | '/verifier/reviews'
    | '/verifier/rooms'
    | '/api/ai/chat'
    | '/api/ai/itinerary'
    | '/api/ai/translate'
    | '/api/bookings/$bookingId'
    | '/api/bookings/my-bookings'
    | '/api/emergency/nearby'
    | '/api/payments/$id'
    | '/api/payments/create-order'
    | '/api/payments/failure'
    | '/api/payments/verify'
    | '/api/provider/bookings'
    | '/api/reviews/$id'
    | '/admin'
    | '/services/$serviceId/book'
    | '/tourist/bookings/$bookingId'
    | '/tourist/payments/$paymentId'
    | '/api/bookings/$bookingId/payment'
    | '/api/reviews/$id/response'
    | '/api/services/$serviceId/availability'
    | '/tourist/bookings'
    | '/tourist/payments'
    | '/tourist/bookings/$bookingId/confirmation'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-guide'
    | '/emergency'
    | '/explore-near-me'
    | '/hotels'
    | '/login'
    | '/mcp'
    | '/planner'
    | '/register'
    | '/restaurants'
    | '/tours'
    | '/translator'
    | '/wishlist'
    | '/_authenticated/admin'
    | '/_authenticated/verifier'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/profile'
    | '/api/bookings'
    | '/api/reviews'
    | '/destinations/$destination'
    | '/guides/$guideId'
    | '/itinerary/$itineraryId'
    | '/services/$serviceId'
    | '/destinations/'
    | '/services/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/providers'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/withdrawals'
    | '/_authenticated/guide/dashboard'
    | '/_authenticated/guide/messages'
    | '/_authenticated/provider/analytics'
    | '/_authenticated/provider/bookings'
    | '/_authenticated/provider/calendar'
    | '/_authenticated/provider/customers'
    | '/_authenticated/provider/dashboard'
    | '/_authenticated/provider/messages'
    | '/_authenticated/provider/notifications'
    | '/_authenticated/provider/profile'
    | '/_authenticated/provider/reviews'
    | '/_authenticated/provider/services'
    | '/_authenticated/provider/wallet'
    | '/_authenticated/tourist/dashboard'
    | '/_authenticated/tourist/itineraries'
    | '/_authenticated/tourist/messages'
    | '/_authenticated/tourist/reviews'
    | '/_authenticated/tourist/wishlist'
    | '/_authenticated/verifier/availability'
    | '/_authenticated/verifier/checkin-checkout'
    | '/_authenticated/verifier/dashboard'
    | '/_authenticated/verifier/guests'
    | '/_authenticated/verifier/hotels'
    | '/_authenticated/verifier/messages'
    | '/_authenticated/verifier/payments'
    | '/_authenticated/verifier/profile'
    | '/_authenticated/verifier/reservations'
    | '/_authenticated/verifier/reviews'
    | '/_authenticated/verifier/rooms'
    | '/api/ai/chat'
    | '/api/ai/itinerary'
    | '/api/ai/translate'
    | '/api/bookings/$bookingId'
    | '/api/bookings/my-bookings'
    | '/api/emergency/nearby'
    | '/api/payments/$id'
    | '/api/payments/create-order'
    | '/api/payments/failure'
    | '/api/payments/verify'
    | '/api/provider/bookings'
    | '/api/reviews/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/services/$serviceId/book'
    | '/_authenticated/tourist/bookings/$bookingId'
    | '/_authenticated/tourist/payments/$paymentId'
    | '/api/bookings/$bookingId/payment'
    | '/api/reviews/$id/response'
    | '/api/services/$serviceId/availability'
    | '/_authenticated/tourist/bookings/'
    | '/_authenticated/tourist/payments/'
    | '/_authenticated/tourist/bookings/$bookingId/confirmation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiGuideRoute: typeof AiGuideRoute
  EmergencyRoute: typeof EmergencyRoute
  ExploreNearMeRoute: typeof ExploreNearMeRoute
  HotelsRoute: typeof HotelsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PlannerRoute: typeof PlannerRoute
  RegisterRoute: typeof RegisterRoute
  RestaurantsRoute: typeof RestaurantsRoute
  ToursRoute: typeof ToursRoute
  TranslatorRoute: typeof TranslatorRoute
  WishlistRoute: typeof WishlistRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiBookingsRoute: typeof ApiBookingsRouteWithChildren
  ApiReviewsRoute: typeof ApiReviewsRouteWithChildren
  DestinationsDestinationRoute: typeof DestinationsDestinationRoute
  GuidesGuideIdRoute: typeof GuidesGuideIdRoute
  ItineraryItineraryIdRoute: typeof ItineraryItineraryIdRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiItineraryRoute: typeof ApiAiItineraryRoute
  ApiAiTranslateRoute: typeof ApiAiTranslateRoute
  ApiEmergencyNearbyRoute: typeof ApiEmergencyNearbyRoute
  ApiPaymentsIdRoute: typeof ApiPaymentsIdRoute
  ApiPaymentsCreateOrderRoute: typeof ApiPaymentsCreateOrderRoute
  ApiPaymentsFailureRoute: typeof ApiPaymentsFailureRoute
  ApiPaymentsVerifyRoute: typeof ApiPaymentsVerifyRoute
  ApiProviderBookingsRoute: typeof ApiProviderBookingsRoute
  ApiServicesServiceIdAvailabilityRoute: typeof ApiServicesServiceIdAvailabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-guide': {
      id: '/ai-guide'
      path: '/ai-guide'
      fullPath: '/ai-guide'
      preLoaderRoute: typeof AiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore-near-me': {
      id: '/explore-near-me'
      path: '/explore-near-me'
      fullPath: '/explore-near-me'
      preLoaderRoute: typeof ExploreNearMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translator': {
      id: '/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof TranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verifier': {
      id: '/_authenticated/verifier'
      path: '/verifier'
      fullPath: '/verifier'
      preLoaderRoute: typeof AuthenticatedVerifierRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews': {
      id: '/api/reviews'
      path: '/api/reviews'
      fullPath: '/api/reviews'
      preLoaderRoute: typeof ApiReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$destination': {
      id: '/destinations/$destination'
      path: '/destinations/$destination'
      fullPath: '/destinations/$destination'
      preLoaderRoute: typeof DestinationsDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guideId': {
      id: '/guides/$guideId'
      path: '/guides/$guideId'
      fullPath: '/guides/$guideId'
      preLoaderRoute: typeof GuidesGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary/$itineraryId': {
      id: '/itinerary/$itineraryId'
      path: '/itinerary/$itineraryId'
      fullPath: '/itinerary/$itineraryId'
      preLoaderRoute: typeof ItineraryItineraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/withdrawals': {
      id: '/_authenticated/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/guide/dashboard': {
      id: '/_authenticated/guide/dashboard'
      path: '/guide/dashboard'
      fullPath: '/guide/dashboard'
      preLoaderRoute: typeof AuthenticatedGuideDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide/messages': {
      id: '/_authenticated/guide/messages'
      path: '/guide/messages'
      fullPath: '/guide/messages'
      preLoaderRoute: typeof AuthenticatedGuideMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/analytics': {
      id: '/_authenticated/provider/analytics'
      path: '/provider/analytics'
      fullPath: '/provider/analytics'
      preLoaderRoute: typeof AuthenticatedProviderAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/bookings': {
      id: '/_authenticated/provider/bookings'
      path: '/provider/bookings'
      fullPath: '/provider/bookings'
      preLoaderRoute: typeof AuthenticatedProviderBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/calendar': {
      id: '/_authenticated/provider/calendar'
      path: '/provider/calendar'
      fullPath: '/provider/calendar'
      preLoaderRoute: typeof AuthenticatedProviderCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/customers': {
      id: '/_authenticated/provider/customers'
      path: '/provider/customers'
      fullPath: '/provider/customers'
      preLoaderRoute: typeof AuthenticatedProviderCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/dashboard': {
      id: '/_authenticated/provider/dashboard'
      path: '/provider/dashboard'
      fullPath: '/provider/dashboard'
      preLoaderRoute: typeof AuthenticatedProviderDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/messages': {
      id: '/_authenticated/provider/messages'
      path: '/provider/messages'
      fullPath: '/provider/messages'
      preLoaderRoute: typeof AuthenticatedProviderMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/notifications': {
      id: '/_authenticated/provider/notifications'
      path: '/provider/notifications'
      fullPath: '/provider/notifications'
      preLoaderRoute: typeof AuthenticatedProviderNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/profile': {
      id: '/_authenticated/provider/profile'
      path: '/provider/profile'
      fullPath: '/provider/profile'
      preLoaderRoute: typeof AuthenticatedProviderProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/reviews': {
      id: '/_authenticated/provider/reviews'
      path: '/provider/reviews'
      fullPath: '/provider/reviews'
      preLoaderRoute: typeof AuthenticatedProviderReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/services': {
      id: '/_authenticated/provider/services'
      path: '/provider/services'
      fullPath: '/provider/services'
      preLoaderRoute: typeof AuthenticatedProviderServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/wallet': {
      id: '/_authenticated/provider/wallet'
      path: '/provider/wallet'
      fullPath: '/provider/wallet'
      preLoaderRoute: typeof AuthenticatedProviderWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tourist/dashboard': {
      id: '/_authenticated/tourist/dashboard'
      path: '/tourist/dashboard'
      fullPath: '/tourist/dashboard'
      preLoaderRoute: typeof AuthenticatedTouristDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tourist/itineraries': {
      id: '/_authenticated/tourist/itineraries'
      path: '/tourist/itineraries'
      fullPath: '/tourist/itineraries'
      preLoaderRoute: typeof AuthenticatedTouristItinerariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tourist/messages': {
      id: '/_authenticated/tourist/messages'
      path: '/tourist/messages'
      fullPath: '/tourist/messages'
      preLoaderRoute: typeof AuthenticatedTouristMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tourist/reviews': {
      id: '/_authenticated/tourist/reviews'
      path: '/tourist/reviews'
      fullPath: '/tourist/reviews'
      preLoaderRoute: typeof AuthenticatedTouristReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tourist/wishlist': {
      id: '/_authenticated/tourist/wishlist'
      path: '/tourist/wishlist'
      fullPath: '/tourist/wishlist'
      preLoaderRoute: typeof AuthenticatedTouristWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verifier/availability': {
      id: '/_authenticated/verifier/availability'
      path: '/availability'
      fullPath: '/verifier/availability'
      preLoaderRoute: typeof AuthenticatedVerifierAvailabilityRouteImport
      parentRoute: typeof AuthenticatedVerifierRouteRoute
    }
    '/_authenticated/verifier/checkin-checkout': {
      id: '/_authenticated/verifier/checkin-checkout'
      path: '/checkin-checkout'
      fullPath: '/verifier/checkin-checkout'
      preLoaderRoute: typeof AuthenticatedVerifierCheckinCheckoutRouteImport
      parentRoute: typeof AuthenticatedVerifierRouteRoute
    }
    '/_authenticated/verifier/dashboard': {
      id: '/_authenticated/verifier/dashboard'
      path: '/dashboard'
      fullPath: '/verifier/dashboard'
      preLoaderRoute: typeof AuthenticatedVerifierDashboardRouteImport
      parentRoute: typeof AuthenticatedVerifierRouteRoute
    }
    '/_authenticated/verifier/guests': {
      id: '/_authenticated/verifier/guests'
      path: '/guests'
      fullPath: '/verifier/guests'
      preLoaderRoute: typeof AuthenticatedVerifierGuestsRouteImport
      parentRoute: typeof AuthenticatedVerifierRouteRoute
    }
    '/_authenticated/verifier/hotels': {
      id: '/_authenticated/verifier/hotels'
      path: '/hotels'
      fullPath: '/verifier/hotels'
      preLoaderRoute: typeof AuthenticatedVerifierHotelsRouteImport
      parentRoute: typeof AuthenticatedVerifierRouteRoute
    }
    '/_authenticated/verifier/messages': {
      id: '/_authenticated/verifier/messages'
      path: '/messages'
      fullPath: '/verifier/messages'
      preLoaderRoute: typeof AuthenticatedVerifierMessagesRouteImport
      parentRoute: typeof AuthenticatedVerifierRouteRoute
    }
    '/_authenticated/verifier/payments': {
      id: '/_authenticated/verifier/payments'
      path: '/payments'
      fullPath: '/verifier/payments'
      preLoaderRoute: typeof AuthenticatedVerifierPaymentsRouteImport
      parentRoute: typeof AuthenticatedVerifierRouteRoute
    }
    '/_authenticated/verifier/profile': {
      id: '/_authenticated/verifier/profile'
      path: '/profile'
      fullPath: '/verifier/profile'
      preLoaderRoute: typeof AuthenticatedVerifierProfileRouteImport
      parentRoute: typeof AuthenticatedVerifierRouteRoute
    }
    '/_authenticated/verifier/reservations': {
      id: '/_authenticated/verifier/reservations'
      path: '/reservations'
      fullPath: '/verifier/reservations'
      preLoaderRoute: typeof AuthenticatedVerifierReservationsRouteImport
      parentRoute: typeof AuthenticatedVerifierRouteRoute
    }
    '/_authenticated/verifier/reviews': {
      id: '/_authenticated/verifier/reviews'
      path: '/reviews'
      fullPath: '/verifier/reviews'
      preLoaderRoute: typeof AuthenticatedVerifierReviewsRouteImport
      parentRoute: typeof AuthenticatedVerifierRouteRoute
    }
    '/_authenticated/verifier/rooms': {
      id: '/_authenticated/verifier/rooms'
      path: '/rooms'
      fullPath: '/verifier/rooms'
      preLoaderRoute: typeof AuthenticatedVerifierRoomsRouteImport
      parentRoute: typeof AuthenticatedVerifierRouteRoute
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/itinerary': {
      id: '/api/ai/itinerary'
      path: '/api/ai/itinerary'
      fullPath: '/api/ai/itinerary'
      preLoaderRoute: typeof ApiAiItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/translate': {
      id: '/api/ai/translate'
      path: '/api/ai/translate'
      fullPath: '/api/ai/translate'
      preLoaderRoute: typeof ApiAiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/$bookingId': {
      id: '/api/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/api/bookings/$bookingId'
      preLoaderRoute: typeof ApiBookingsBookingIdRouteImport
      parentRoute: typeof ApiBookingsRoute
    }
    '/api/bookings/my-bookings': {
      id: '/api/bookings/my-bookings'
      path: '/my-bookings'
      fullPath: '/api/bookings/my-bookings'
      preLoaderRoute: typeof ApiBookingsMyBookingsRouteImport
      parentRoute: typeof ApiBookingsRoute
    }
    '/api/emergency/nearby': {
      id: '/api/emergency/nearby'
      path: '/api/emergency/nearby'
      fullPath: '/api/emergency/nearby'
      preLoaderRoute: typeof ApiEmergencyNearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/$id': {
      id: '/api/payments/$id'
      path: '/api/payments/$id'
      fullPath: '/api/payments/$id'
      preLoaderRoute: typeof ApiPaymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/create-order': {
      id: '/api/payments/create-order'
      path: '/api/payments/create-order'
      fullPath: '/api/payments/create-order'
      preLoaderRoute: typeof ApiPaymentsCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/failure': {
      id: '/api/payments/failure'
      path: '/api/payments/failure'
      fullPath: '/api/payments/failure'
      preLoaderRoute: typeof ApiPaymentsFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/verify': {
      id: '/api/payments/verify'
      path: '/api/payments/verify'
      fullPath: '/api/payments/verify'
      preLoaderRoute: typeof ApiPaymentsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider/bookings': {
      id: '/api/provider/bookings'
      path: '/api/provider/bookings'
      fullPath: '/api/provider/bookings'
      preLoaderRoute: typeof ApiProviderBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/$id': {
      id: '/api/reviews/$id'
      path: '/$id'
      fullPath: '/api/reviews/$id'
      preLoaderRoute: typeof ApiReviewsIdRouteImport
      parentRoute: typeof ApiReviewsRoute
    }
    '/_authenticated/services/$serviceId/book': {
      id: '/_authenticated/services/$serviceId/book'
      path: '/services/$serviceId/book'
      fullPath: '/services/$serviceId/book'
      preLoaderRoute: typeof AuthenticatedServicesServiceIdBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tourist/bookings/': {
      id: '/_authenticated/tourist/bookings/'
      path: '/tourist/bookings'
      fullPath: '/tourist/bookings/'
      preLoaderRoute: typeof AuthenticatedTouristBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tourist/bookings/$bookingId': {
      id: '/_authenticated/tourist/bookings/$bookingId'
      path: '/tourist/bookings/$bookingId'
      fullPath: '/tourist/bookings/$bookingId'
      preLoaderRoute: typeof AuthenticatedTouristBookingsBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tourist/payments/': {
      id: '/_authenticated/tourist/payments/'
      path: '/tourist/payments'
      fullPath: '/tourist/payments/'
      preLoaderRoute: typeof AuthenticatedTouristPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tourist/payments/$paymentId': {
      id: '/_authenticated/tourist/payments/$paymentId'
      path: '/tourist/payments/$paymentId'
      fullPath: '/tourist/payments/$paymentId'
      preLoaderRoute: typeof AuthenticatedTouristPaymentsPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/bookings/$bookingId/payment': {
      id: '/api/bookings/$bookingId/payment'
      path: '/payment'
      fullPath: '/api/bookings/$bookingId/payment'
      preLoaderRoute: typeof ApiBookingsBookingIdPaymentRouteImport
      parentRoute: typeof ApiBookingsBookingIdRoute
    }
    '/api/reviews/$id/response': {
      id: '/api/reviews/$id/response'
      path: '/response'
      fullPath: '/api/reviews/$id/response'
      preLoaderRoute: typeof ApiReviewsIdResponseRouteImport
      parentRoute: typeof ApiReviewsIdRoute
    }
    '/api/services/$serviceId/availability': {
      id: '/api/services/$serviceId/availability'
      path: '/api/services/$serviceId/availability'
      fullPath: '/api/services/$serviceId/availability'
      preLoaderRoute: typeof ApiServicesServiceIdAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tourist/bookings/$bookingId/confirmation': {
      id: '/_authenticated/tourist/bookings/$bookingId/confirmation'
      path: '/confirmation'
      fullPath: '/tourist/bookings/$bookingId/confirmation'
      preLoaderRoute: typeof AuthenticatedTouristBookingsBookingIdConfirmationRouteImport
      parentRoute: typeof AuthenticatedTouristBookingsBookingIdRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
    AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
    AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedVerifierRouteRouteChildren {
  AuthenticatedVerifierAvailabilityRoute: typeof AuthenticatedVerifierAvailabilityRoute
  AuthenticatedVerifierCheckinCheckoutRoute: typeof AuthenticatedVerifierCheckinCheckoutRoute
  AuthenticatedVerifierDashboardRoute: typeof AuthenticatedVerifierDashboardRoute
  AuthenticatedVerifierGuestsRoute: typeof AuthenticatedVerifierGuestsRoute
  AuthenticatedVerifierHotelsRoute: typeof AuthenticatedVerifierHotelsRoute
  AuthenticatedVerifierMessagesRoute: typeof AuthenticatedVerifierMessagesRoute
  AuthenticatedVerifierPaymentsRoute: typeof AuthenticatedVerifierPaymentsRoute
  AuthenticatedVerifierProfileRoute: typeof AuthenticatedVerifierProfileRoute
  AuthenticatedVerifierReservationsRoute: typeof AuthenticatedVerifierReservationsRoute
  AuthenticatedVerifierReviewsRoute: typeof AuthenticatedVerifierReviewsRoute
  AuthenticatedVerifierRoomsRoute: typeof AuthenticatedVerifierRoomsRoute
}

const AuthenticatedVerifierRouteRouteChildren: AuthenticatedVerifierRouteRouteChildren =
  {
    AuthenticatedVerifierAvailabilityRoute:
      AuthenticatedVerifierAvailabilityRoute,
    AuthenticatedVerifierCheckinCheckoutRoute:
      AuthenticatedVerifierCheckinCheckoutRoute,
    AuthenticatedVerifierDashboardRoute: AuthenticatedVerifierDashboardRoute,
    AuthenticatedVerifierGuestsRoute: AuthenticatedVerifierGuestsRoute,
    AuthenticatedVerifierHotelsRoute: AuthenticatedVerifierHotelsRoute,
    AuthenticatedVerifierMessagesRoute: AuthenticatedVerifierMessagesRoute,
    AuthenticatedVerifierPaymentsRoute: AuthenticatedVerifierPaymentsRoute,
    AuthenticatedVerifierProfileRoute: AuthenticatedVerifierProfileRoute,
    AuthenticatedVerifierReservationsRoute:
      AuthenticatedVerifierReservationsRoute,
    AuthenticatedVerifierReviewsRoute: AuthenticatedVerifierReviewsRoute,
    AuthenticatedVerifierRoomsRoute: AuthenticatedVerifierRoomsRoute,
  }

const AuthenticatedVerifierRouteRouteWithChildren =
  AuthenticatedVerifierRouteRoute._addFileChildren(
    AuthenticatedVerifierRouteRouteChildren,
  )

interface AuthenticatedTouristBookingsBookingIdRouteChildren {
  AuthenticatedTouristBookingsBookingIdConfirmationRoute: typeof AuthenticatedTouristBookingsBookingIdConfirmationRoute
}

const AuthenticatedTouristBookingsBookingIdRouteChildren: AuthenticatedTouristBookingsBookingIdRouteChildren =
  {
    AuthenticatedTouristBookingsBookingIdConfirmationRoute:
      AuthenticatedTouristBookingsBookingIdConfirmationRoute,
  }

const AuthenticatedTouristBookingsBookingIdRouteWithChildren =
  AuthenticatedTouristBookingsBookingIdRoute._addFileChildren(
    AuthenticatedTouristBookingsBookingIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedVerifierRouteRoute: typeof AuthenticatedVerifierRouteRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedGuideDashboardRoute: typeof AuthenticatedGuideDashboardRoute
  AuthenticatedGuideMessagesRoute: typeof AuthenticatedGuideMessagesRoute
  AuthenticatedProviderAnalyticsRoute: typeof AuthenticatedProviderAnalyticsRoute
  AuthenticatedProviderBookingsRoute: typeof AuthenticatedProviderBookingsRoute
  AuthenticatedProviderCalendarRoute: typeof AuthenticatedProviderCalendarRoute
  AuthenticatedProviderCustomersRoute: typeof AuthenticatedProviderCustomersRoute
  AuthenticatedProviderDashboardRoute: typeof AuthenticatedProviderDashboardRoute
  AuthenticatedProviderMessagesRoute: typeof AuthenticatedProviderMessagesRoute
  AuthenticatedProviderNotificationsRoute: typeof AuthenticatedProviderNotificationsRoute
  AuthenticatedProviderProfileRoute: typeof AuthenticatedProviderProfileRoute
  AuthenticatedProviderReviewsRoute: typeof AuthenticatedProviderReviewsRoute
  AuthenticatedProviderServicesRoute: typeof AuthenticatedProviderServicesRoute
  AuthenticatedProviderWalletRoute: typeof AuthenticatedProviderWalletRoute
  AuthenticatedTouristDashboardRoute: typeof AuthenticatedTouristDashboardRoute
  AuthenticatedTouristItinerariesRoute: typeof AuthenticatedTouristItinerariesRoute
  AuthenticatedTouristMessagesRoute: typeof AuthenticatedTouristMessagesRoute
  AuthenticatedTouristReviewsRoute: typeof AuthenticatedTouristReviewsRoute
  AuthenticatedTouristWishlistRoute: typeof AuthenticatedTouristWishlistRoute
  AuthenticatedServicesServiceIdBookRoute: typeof AuthenticatedServicesServiceIdBookRoute
  AuthenticatedTouristBookingsBookingIdRoute: typeof AuthenticatedTouristBookingsBookingIdRouteWithChildren
  AuthenticatedTouristPaymentsPaymentIdRoute: typeof AuthenticatedTouristPaymentsPaymentIdRoute
  AuthenticatedTouristBookingsIndexRoute: typeof AuthenticatedTouristBookingsIndexRoute
  AuthenticatedTouristPaymentsIndexRoute: typeof AuthenticatedTouristPaymentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedVerifierRouteRoute: AuthenticatedVerifierRouteRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedGuideDashboardRoute: AuthenticatedGuideDashboardRoute,
  AuthenticatedGuideMessagesRoute: AuthenticatedGuideMessagesRoute,
  AuthenticatedProviderAnalyticsRoute: AuthenticatedProviderAnalyticsRoute,
  AuthenticatedProviderBookingsRoute: AuthenticatedProviderBookingsRoute,
  AuthenticatedProviderCalendarRoute: AuthenticatedProviderCalendarRoute,
  AuthenticatedProviderCustomersRoute: AuthenticatedProviderCustomersRoute,
  AuthenticatedProviderDashboardRoute: AuthenticatedProviderDashboardRoute,
  AuthenticatedProviderMessagesRoute: AuthenticatedProviderMessagesRoute,
  AuthenticatedProviderNotificationsRoute:
    AuthenticatedProviderNotificationsRoute,
  AuthenticatedProviderProfileRoute: AuthenticatedProviderProfileRoute,
  AuthenticatedProviderReviewsRoute: AuthenticatedProviderReviewsRoute,
  AuthenticatedProviderServicesRoute: AuthenticatedProviderServicesRoute,
  AuthenticatedProviderWalletRoute: AuthenticatedProviderWalletRoute,
  AuthenticatedTouristDashboardRoute: AuthenticatedTouristDashboardRoute,
  AuthenticatedTouristItinerariesRoute: AuthenticatedTouristItinerariesRoute,
  AuthenticatedTouristMessagesRoute: AuthenticatedTouristMessagesRoute,
  AuthenticatedTouristReviewsRoute: AuthenticatedTouristReviewsRoute,
  AuthenticatedTouristWishlistRoute: AuthenticatedTouristWishlistRoute,
  AuthenticatedServicesServiceIdBookRoute:
    AuthenticatedServicesServiceIdBookRoute,
  AuthenticatedTouristBookingsBookingIdRoute:
    AuthenticatedTouristBookingsBookingIdRouteWithChildren,
  AuthenticatedTouristPaymentsPaymentIdRoute:
    AuthenticatedTouristPaymentsPaymentIdRoute,
  AuthenticatedTouristBookingsIndexRoute:
    AuthenticatedTouristBookingsIndexRoute,
  AuthenticatedTouristPaymentsIndexRoute:
    AuthenticatedTouristPaymentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiBookingsBookingIdRouteChildren {
  ApiBookingsBookingIdPaymentRoute: typeof ApiBookingsBookingIdPaymentRoute
}

const ApiBookingsBookingIdRouteChildren: ApiBookingsBookingIdRouteChildren = {
  ApiBookingsBookingIdPaymentRoute: ApiBookingsBookingIdPaymentRoute,
}

const ApiBookingsBookingIdRouteWithChildren =
  ApiBookingsBookingIdRoute._addFileChildren(ApiBookingsBookingIdRouteChildren)

interface ApiBookingsRouteChildren {
  ApiBookingsBookingIdRoute: typeof ApiBookingsBookingIdRouteWithChildren
  ApiBookingsMyBookingsRoute: typeof ApiBookingsMyBookingsRoute
}

const ApiBookingsRouteChildren: ApiBookingsRouteChildren = {
  ApiBookingsBookingIdRoute: ApiBookingsBookingIdRouteWithChildren,
  ApiBookingsMyBookingsRoute: ApiBookingsMyBookingsRoute,
}

const ApiBookingsRouteWithChildren = ApiBookingsRoute._addFileChildren(
  ApiBookingsRouteChildren,
)

interface ApiReviewsIdRouteChildren {
  ApiReviewsIdResponseRoute: typeof ApiReviewsIdResponseRoute
}

const ApiReviewsIdRouteChildren: ApiReviewsIdRouteChildren = {
  ApiReviewsIdResponseRoute: ApiReviewsIdResponseRoute,
}

const ApiReviewsIdRouteWithChildren = ApiReviewsIdRoute._addFileChildren(
  ApiReviewsIdRouteChildren,
)

interface ApiReviewsRouteChildren {
  ApiReviewsIdRoute: typeof ApiReviewsIdRouteWithChildren
}

const ApiReviewsRouteChildren: ApiReviewsRouteChildren = {
  ApiReviewsIdRoute: ApiReviewsIdRouteWithChildren,
}

const ApiReviewsRouteWithChildren = ApiReviewsRoute._addFileChildren(
  ApiReviewsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiGuideRoute: AiGuideRoute,
  EmergencyRoute: EmergencyRoute,
  ExploreNearMeRoute: ExploreNearMeRoute,
  HotelsRoute: HotelsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PlannerRoute: PlannerRoute,
  RegisterRoute: RegisterRoute,
  RestaurantsRoute: RestaurantsRoute,
  ToursRoute: ToursRoute,
  TranslatorRoute: TranslatorRoute,
  WishlistRoute: WishlistRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiBookingsRoute: ApiBookingsRouteWithChildren,
  ApiReviewsRoute: ApiReviewsRouteWithChildren,
  DestinationsDestinationRoute: DestinationsDestinationRoute,
  GuidesGuideIdRoute: GuidesGuideIdRoute,
  ItineraryItineraryIdRoute: ItineraryItineraryIdRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiItineraryRoute: ApiAiItineraryRoute,
  ApiAiTranslateRoute: ApiAiTranslateRoute,
  ApiEmergencyNearbyRoute: ApiEmergencyNearbyRoute,
  ApiPaymentsIdRoute: ApiPaymentsIdRoute,
  ApiPaymentsCreateOrderRoute: ApiPaymentsCreateOrderRoute,
  ApiPaymentsFailureRoute: ApiPaymentsFailureRoute,
  ApiPaymentsVerifyRoute: ApiPaymentsVerifyRoute,
  ApiProviderBookingsRoute: ApiProviderBookingsRoute,
  ApiServicesServiceIdAvailabilityRoute: ApiServicesServiceIdAvailabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
