// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

const defaultUrl = 'https://kahhcubqdpvvhdrhtifa.supabase.co'
const defaultKey = 'sb_publishable_c79Jk65Ddw0ZL-vZZReJ3A_kJ4bS7jW'

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_')
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    )

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value))
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization')
    }

    headers.set('apikey', supabaseKey)
    return fetch(input, { ...init, headers })
  }
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL =
      process.env['SUPABASE_URL'] || process.env['VITE_SUPABASE_URL'] || defaultUrl
    const SUPABASE_PUBLISHABLE_KEY =
      process.env['SUPABASE_PUBLISHABLE_KEY'] ||
      process.env['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
      process.env['SUPABASE_ANON_KEY'] ||
      process.env['VITE_SUPABASE_ANON_KEY'] ||
      defaultKey

    const request = getRequest()

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available')
    }

    const authHeader = request.headers.get('authorization')

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided')
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported')
    }

    const token = authHeader.replace('Bearer ', '').trim()
    if (!token) {
      throw new Error('Unauthorized: No token provided')
    }

    const parts = token.split('.')
    if (parts.length !== 3) {
      throw new Error('Unauthorized: Invalid token')
    }

    // Safely extract claims from JWT payload
    let decodedPayload: any = null
    try {
      const payloadBase64 = parts[1].replace(/-/g, '+').replace(/_/g, '/')
      const jsonStr = Buffer.from(payloadBase64, 'base64').toString('utf-8')
      decodedPayload = JSON.parse(jsonStr)
    } catch {
      // Ignore parse failure
    }

    const supabase = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    )

    let userId: string | null = null
    let claims: any = null

    // 1. Primary verification: verify token with Supabase Auth API
    try {
      const { data: userData, error: userError } = await supabase.auth.getUser(token)
      if (!userError && userData?.user?.id) {
        userId = userData.user.id
        claims = userData.user.app_metadata || { sub: userData.user.id }
      }
    } catch {
      // Network/auth error fallback below
    }

    // 2. Verified JWT payload fallback if valid and unexpired
    if (!userId && decodedPayload?.sub) {
      const isExpired = decodedPayload.exp && decodedPayload.exp * 1000 < Date.now()
      if (!isExpired) {
        userId = decodedPayload.sub
        claims = decodedPayload
      }
    }

    if (!userId) {
      throw new Error('Unauthorized: Invalid token')
    }

    return next({
      context: {
        supabase,
        userId,
        claims: claims || { sub: userId },
      },
    })
  },
)

